### ISSUE TITLE
Roadmap after 0.2

### ISSUE THREAD

**Issue by spirali** [substantic/rain#26]
We have received many feedbacks from our reddit post (https://www.reddit.com/r/rust/comments/89yppv/rain_rust_based_computational_framework/). I think that now is time to recap our plans and maybe reconsider priorities to reflect real needs of users. This is meant as a kind of brainstorming white board; each individal task should have own issue at the end. Also, I would like to focus on a relatively short term road plan (let us say things that could be finished within 3 months), maybe we can create a similar post for our long term plans.

**EDIT (gavento):** Moved @spirali's TODO to a post below.

**Comment by spirali** [comment]
Is "Python subworker as a library" necessary? I have the feeling that for each environment where we can transfer a function to a subworker from a client in reasonable (and portable) way then we should do it that way. The overhead of transferring a function is minimal (it is done only once) and flexibility is huge. I consider building a "fixed" subworker as a kind of side-step where there is no such option (C++/Rust [?*])

* Having a possibility to annotate a rust function in a Rust client and send it to a generic Rust subworker would be a killing feature, but I do not know if this is possible

**Comment by gavento** [comment]
I can imagine some scenarios where a python worker could be useful:

* When your task code is extensive and stable across pipelines. Now you need to somehow import it and let cloudpickle transfer it. (Not really elegant.)
* When you have a Python 2.7 (legacy scientific code) or Pypy (for speed) code to be run. We can probably make the subworker Python2 compatible relatively easily if we want.
* When you have cython or other binary extensions (does cloudpickle transfer them reliably / at all?). Even if you deploy the binaries manually, you may have a different python ABI version on the workers than on your client.

Also, the built-in pytask subworker can be trivially implemented as one such subworker task (with a bit of unpacking logic) and so it is not much more work.

**Comment by spirali** [comment]
* I think that even you have a stable pipeline then sending it to subworkers costs nothing (especially compared to the fact that you use Python) and setting up the infrastructure with own subworkers is always more painful (admin work, changes & updates).

* Pypy actually works right now - there is no problem to cloudpickle an object in CPython and unpickle it in Pypy. Capnp works in pypy.

* Cloudpickle transports Python bytecode not binary code, so if you have a library installed on both ends, there is no ABI problem.

However, I see now that it can be useful to define tasks that may be called e.g. from Java client where cloudpickle is not easily accessible.

**Comment by spirali** [comment]
PR #40 implements replacement of DataStore API with direct calls

**Comment by vojtechcima** [comment]
PR #52 implements Exoscale deployment scripts.

**Comment by yingfeng** [comment]
These are what I think useful in future:
- Being able to be orchestrated by Kubernetes
- Provide compatible api with popular python libraries, including sklearn, numpy, and pandas, for example, some ideas from [dask](https://github.com/dask) could be borrowed, which is a distributed data process framework with those compatible apis. However, dask suffers from performance as well as fault tolerancy. As @gavento listed above, integration with XGBoost or other machine learning libraries are required in future, however, the integration would not be that useful without such design which would be used to serve as the data pre-processing for those machine learning libraries.  On the other hand, spark is a good contender

**Comment by gavento** [comment]
Transitioned to #64 after v0.3 release
