### ISSUE TITLE
dependency problem of crate log 0.3.x

### ISSUE THREAD

**Issue by aimof** [substantic/rain#29]
When rain is built or installed with log 0.3.x, it fails.

```
error[E0432]: unresolved import `log::Level`
   --> src/bin.rs:349:21
    |
349 |                 use log::Level;
    |                     ^^^^^^^^^^ no `Level` in the root

error: aborting due to previous error
```

It seems to depend on a change [rust-lang-nursery/log#162](https://github.com/rust-lang-nursery/log/pull/162).  So If we use log 0.4.x,  build or install success.

So, we should change `"*"` in Cargo.toml to `>=0.4`.
I'll make a PR.

**Comment by spirali** [comment]
You are right. I though that it was solved by Cargo.lock where v0.4 is "locked", but somehow it is not respected in your case.

**Comment by spirali** [comment]
Thank you for reporting and PR.
