### ISSUE TITLE
Attributes refactor and specification

### ISSUE THREAD

**Issue by gavento** [substantic/rain#59]
The attributes are currently not well-specified and there seem to be ways to implement them better before we release the (much more stable) v0.3.

Goals:
* Rust structures (with serde) with typed values for known attributes (and a map for user/unknown)
* Split Task and DataObject attributes (required by the above, will allow checking in Python and other clients)
* Specify a fixed encoding for rich and user-specified values (current proposal: JSON with base64 binary data) (note that non-trivial binary data in attributes are generally discouraged)
* Create a rich Attributes class in Python (underway in #60)
* Fix and document the new structure semantics

**Comment by spirali** [comment]
Schema for spec/info transfers
![archspec svg](https://user-images.githubusercontent.com/263349/40743061-c9056e9c-6450-11e8-97e1-3aaa2140cbf3.png)

**Comment by gavento** [comment]
Resolved in v0.3 both in client, server and executor, documentation updated to describe individual attributes.
