### ISSUE TITLE
Python client segfaults with server running under WSL

### ISSUE THREAD

**Issue by doxxx** [substantic/rain#69]
I tried executing the example from the README using Windows Subsystem for Linux. The server starts up with no apparent errors but executing the Python client script results in the client crashing with a SIGSEGV address boundary error. I tried running it with `strace` but there nothing obvious in the output. I can include the strace output if you want, but I'm not sure what other information I can gather to help diagnose.

I'm using Windows 10 Enterprise 10.0.16299 with Ubuntu 16.04 in WSL. Something to note is that I had to install the `cython` system package before running `pip3 install rain-python`. I used virtualenv to create a virtualized Python install into which I installed `rain-python`.

Testing the same, but without the virtualized Python, in a Ubuntu 16.04 Docker container works so it's something to do with WSL.

Is it possible to get the server working on Windows directly? I tried compiling it but it makes use of crates that provide Unix-only functions like gethostname. Is there no cross-platform equivalent in Rust std or another crate?

**Comment by spirali** [comment]
Please set the environment variable to RUST_LOG=debug. This should produce a more detailed log. If you are using "rain start", you can find logs by default in /tmp/rain-logs/rain-XXXX. This should help us to diagnose the problem.

The main obstacle for native Windows build is some machinery in governors around executing external programs and data object mapping; it uses symlinks and unix permissions. I believe that with some work, all these things are portable. However, AFAIK a windows port is not a priority for any of the core developers.

Thank you for report!

**Comment by doxxx** [comment]
I collected more detailed logs and I see the client connecting but it drops connection immediately. I tried running the Python client example interactively and it crashes on the line where it creates a Client instance.

The `strace` output just before the crash looks like this:

```
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=552, ...}) = 0
read(3, "# This file is automatically gen"..., 512) = 512
read(3, "::1 ip6-allnodes\nff02::2 ip6-all"..., 512) = 40
read(3, "", 512)                        = 0
close(3)                                = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(7210), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
clock_gettime(CLOCK_MONOTONIC, {87679, 563566000}) = 0
rt_sigprocmask(SIG_BLOCK, [USR1], NULL, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7fb979a454b0}, {SIG_IGN, [], SA_RESTORER, 0x7fb979df1390}, 8) = 0
futex(0x7fb97818f044, FUTEX_WAKE_PRIVATE, 2147483647) = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
futex(0x7fb979dd8110, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fb9778c5680, FUTEX_WAKE_PRIVATE, 2147483647) = 0
close(4)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
```

Running the Python client in `gdb`, trapping SIGSEGV, I got the following backtrace:

```
Catchpoint 1 (signal SIGSEGV), __pyx_pf_5capnp_3lib_5capnp_16_FdAsyncIoStream___init__ (__pyx_v_fd=<optimized out>,
    __pyx_v_self=0x7ffffc1b0678) at capnp/lib/capnp.cpp:53562
53562   capnp/lib/capnp.cpp: No such file or directory.
(gdb) bt
#0  __pyx_pf_5capnp_3lib_5capnp_16_FdAsyncIoStream___init__ (__pyx_v_fd=<optimized out>, __pyx_v_self=0x7ffffc1b0678)
    at capnp/lib/capnp.cpp:53562
#1  __pyx_pw_5capnp_3lib_5capnp_16_FdAsyncIoStream_1__init__ (__pyx_v_self=0x7ffffc1b0678, __pyx_args=<optimized out>,
    __pyx_kwds=<optimized out>) at capnp/lib/capnp.cpp:53532
#2  0x000000000057f03c in ?? ()
#3  0x00007ffffd2a22d1 in __Pyx_PyObject_Call (kw=0x0, arg=<optimized out>,
    func=0x7ffffd685fc0 <__pyx_type_5capnp_3lib_5capnp__FdAsyncIoStream>) at capnp/lib/capnp.cpp:91477
#4  __pyx_pf_5capnp_3lib_5capnp_14TwoPartyClient___init__ (__pyx_v_nesting_limit=<optimized out>,
    __pyx_v_traversal_limit_in_words=<optimized out>, __pyx_v_restorer=<optimized out>, __pyx_v_socket=0x7ffffc1b40a8,
    __pyx_v_self=0x7ffffc208d58) at capnp/lib/capnp.cpp:48906
#5  __pyx_pw_5capnp_3lib_5capnp_14TwoPartyClient_1__init__ (__pyx_v_self=0x7ffffc208d58, __pyx_args=<optimized out>,
    __pyx_kwds=<optimized out>) at capnp/lib/capnp.cpp:48802
#6  0x000000000057f03c in ?? ()
#7  0x00000000005c1797 in PyObject_Call ()
#8  0x000000000053bba6 in PyEval_EvalFrameEx ()
#9  0x0000000000540f9b in PyEval_EvalCodeEx ()
#10 0x00000000004ebd23 in ?? ()
#11 0x00000000005c1797 in PyObject_Call ()
#12 0x00000000004fb9ce in ?? ()
#13 0x00000000005c1797 in PyObject_Call ()
#14 0x0000000000574999 in ?? ()
#15 0x000000000057f03c in ?? ()
#16 0x00000000005c1797 in PyObject_Call ()
#17 0x000000000053bba6 in PyEval_EvalFrameEx ()
#18 0x0000000000540199 in ?? ()
#19 0x0000000000540e4f in PyEval_EvalCode ()
#20 0x000000000060c272 in ?? ()
#21 0x000000000060e71a in PyRun_FileExFlags ()
#22 0x000000000060ef0c in PyRun_SimpleFileExFlags ()
---Type <return> to continue, or q <return> to quit---
#23 0x000000000063fb26 in Py_Main ()
#24 0x00000000004cfeb1 in main ()
```

**Comment by doxxx** [comment]
Looks like [capnp doesn't work on WSL](https://github.com/capnproto/capnproto/issues/458) due to missing support for some syscalls, but it would appear that this has been [fixed in an upcoming version of WSL](https://github.com/Microsoft/WSL/issues/129).

As such, I think it's out of your hands.

**Comment by spirali** [comment]
Thank you for your update. We are actually replacing capnp, but it is still quite a long way.

**Comment by vojtechcima** [comment]
I think the easiest way to get started with Rain on a Windows machine is using Docker. You can either build the Docker image yourself using the provided [Dockerfile](https://github.com/substantic/rain/blob/master/Dockerfile) or [pull it](https://hub.docker.com/r/substantic/rain/) from Docker hub.
